import {
  Example01HelloWorld,
  Example02VirtualFs,
  Example03SpawnProcess,
  Example04CodeEditor,
  Example05NetworkSandbox,
  Example06LowLevelApi,
  Example07BunServeBasic,
  Example08BunServeRoutes,
  Example09BunServeStreaming,
  Example10BunServeWebsocket,
  Example11BunServeTls,
  Example12BunInstall,
  Example13PluginNetHttp,
  Example14HonoServer,
  Example15HttpNetTls,
  Example16FileIo,
  Example17PluginLifecycle,
  Example18ViteReact,
  Example19BunInstallWorkspaces,
  Example20BunAdd,
} from './examples'

export const examples = [
  {
    path: '/01-hello-world',
    label: '01 — Hello World',
    description: 'Create a container and run a script.',
    Component: Example01HelloWorld,
  },
  {
    path: '/02-virtual-fs',
    label: '02 — Virtual FS',
    description: 'File I/O, directories, and mounting files.',
    Component: Example02VirtualFs,
  },
  {
    path: '/03-spawn-process',
    label: '03 — Spawn Process',
    description: 'Long-running process with streaming output.',
    Component: Example03SpawnProcess,
  },
  {
    path: '/04-code-editor',
    label: '04 — Code Editor',
    description: 'Minimal browser editor running TypeScript.',
    Component: Example04CodeEditor,
  },
  {
    path: '/05-network-sandbox',
    label: '05 — Network Sandbox',
    description: 'Allowed hosts and Service Worker proxy.',
    Component: Example05NetworkSandbox,
  },
  {
    path: '/06-low-level-api',
    label: '06 — Low-Level API',
    description: 'Use WasmHost and WASI shim directly.',
    Component: Example06LowLevelApi,
  },
  {
    path: '/07-bun-serve-basic',
    label: '07 — Bun.serve Basic',
    description: 'Start a Bun.serve server and fetch.',
    Component: Example07BunServeBasic,
  },
  {
    path: '/08-bun-serve-routes',
    label: '08 — Bun.serve Routes',
    description: 'Routes, headers, JSON responses.',
    Component: Example08BunServeRoutes,
  },
  {
    path: '/09-bun-serve-streaming',
    label: '09 — Bun.serve Streaming',
    description: 'Streamed responses from Bun.serve.',
    Component: Example09BunServeStreaming,
  },
  {
    path: '/10-bun-serve-websocket',
    label: '10 — Bun.serve WebSocket',
    description: 'Best-effort WebSocket proxy.',
    Component: Example10BunServeWebsocket,
  },
  {
    path: '/11-bun-serve-tls',
    label: '11 — Bun.serve TLS',
    description: 'HTTPS proxy via Service Worker.',
    Component: Example11BunServeTls,
  },
  {
    path: '/12-bun-install',
    label: '12 — Bun Install',
    description: 'Install a package through proxy registry.',
    Component: Example12BunInstall,
  },
  {
    path: '/13-plugin-net-http',
    label: '13 — Plugin net/http',
    description: 'Plugin intercept for net/http modules.',
    Component: Example13PluginNetHttp,
  },
  {
    path: '/14-hono-server',
    label: '14 — Hono Server',
    description: 'Install and serve a Hono app.',
    Component: Example14HonoServer,
  },
  {
    path: '/15-http-net-tls',
    label: '15 — HTTP + net/tls',
    description: 'HTTP client and socket proxies.',
    Component: Example15HttpNetTls,
  },
  {
    path: '/16-file-io',
    label: '16 — File IO',
    description: 'Bun.file and Bun.write demos.',
    Component: Example16FileIo,
  },
  {
    path: '/17-plugin-lifecycle',
    label: '17 — Plugin Lifecycle',
    description: 'Runtime lifecycle hooks.',
    Component: Example17PluginLifecycle,
  },
  {
    path: '/18-vite-react',
    label: '18 — Vite + React',
    description: 'Manage a React app in the container.',
    Component: Example18ViteReact,
  },
  {
    path: '/19-bun-install-workspaces',
    label: '19 — Bun Install Workspaces',
    description: 'Install workspace and registry deps.',
    Component: Example19BunInstallWorkspaces,
  },
  {
    path: '/20-bun-add',
    label: '20 — Bun Add',
    description: 'Add dependencies with bun add.',
    Component: Example20BunAdd,
  },
]
